server:
  port: 9002
spring:
  application:
    name: kafka
  # ??kafka server?????????????????
  kafka:
    bootstrap-servers: 192.168.192.127:19092,192.168.192.127:29092,192.168.192.127:39092,192.168.192.128:19092,192.168.192.128:29092,192.168.192.128:39092
#### kafka????? start ####
# ???????group id --> ???kafka???????consumer?????????????groud.id????
    consumer:
      group-id: test1
# smallest?largest??????smallest??0????????largest?logfile?offset??????????????smallest
      auto-offset-reset: earliest
# enable.auto.commit:true --> ??????offset
      enable-auto-commit: true
#??'enable.auto.commit'?true????????????Kafka????????????????5000?
      auto-commit-interval: 1000
# ????key??????????
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#### kafka????? end ####