server:
  port: 9003
spring:
  application:
    name: kafka
  # ??kafka server?????????????????
  kafka:
    bootstrap-servers: 192.168.22.252:19092,192.168.22.252:29092,192.168.22.252:39092
#### kafka????? start ####
# ???????group id --> ???kafka???????consumer?????????????groud.id????
    consumer:
      group-id: test1
# smallest?largest??????smallest??0????????largest?logfile?offset??????????????smallest
      auto-offset-reset: earliest
# enable.auto.commit:true --> ??????offset
      enable-auto-commit: true
#??'enable.auto.commit'?true????????????Kafka????????????????5000?
      auto-commit-interval: 1000
# ????key??????????
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  logs:
    kafka:
      bootstrap-servers: 192.168.22.211:32092
      consumer:
        group-id: test1
        # smallest?largest??????smallest??0????????largest?logfile?offset??????????????smallest
        auto-offset-reset: earliest
        # enable.auto.commit:true --> ??????offset
        enable-auto-commit: true
        #??'enable.auto.commit'?true????????????Kafka????????????????5000?
        auto-commit-interval: 1000
        # ????key??????????
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#### kafka????? end ####
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: info
    root: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS,GMT+8} %level [%thread] [%X{traceId}] %logger{100} %C %L - %msg %ex%n'
  file:
    name: D:/fastcloud/logs/kafkaconsumer.log
  logback:
    rollingpolicy:
      max-file-size: 3GB